# Generated by Django 5.0 on 2023-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=5000)),
            ],
        ),
    ]
